layout_spectrum: 0.7706767
typography_spectrum: 0.8266307
color:
  saturation: 0.2730796
  brandStrength: 0.784574
  lightness: 0.7260264
  brandColors:
    - '#42764A'
    - '#201E1F'
    - '#D7C7B5'
    - '#A48F77'
    - '#FBF3F2'
  rhythmicContrast: 0.7531928
name: tokuyamaeikaiwa.com
